// angular_6_complete_guide/course_project/src/app/header/header.component.ts
import { Component, OnInit, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  @Output() featureSelected = new EventEmitter<string>();

  onSelect(feature: string) {
    this.featureSelected.emit(feature);
  }

  constructor() { }

  ngOnInit() {
  }

}

<nav class="navbar navbar-expand-md navbar-light bg-light mb-2">
  <a href="#" class="navbar-brand">Recipe Book</a>

  <button class="navbar-toggler hidden-sm-up" type="button" (click)="isNavbarCollapsed = !isNavbarCollapsed" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div [ngbCollapse]="!isNavbarCollapsed" class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" (click)="onSelect('recipe')">Recipes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" (click)="onSelect('shopping-list')">Shopping List</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto pr-md-5">
      <li class="nav-item dropdown" ngbDropdown>
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false" ngbDropdownToggle>Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown" ngbDropdownMenu>
          <a class="dropdown-item" href="#">Save Data</a>
          <a class="dropdown-item" href="#">Fetch Data</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

// vuejs/vuejs_routing/src/components/Header.vue
<template>
  <nav class="navbar navbar-expand-lg navbar-dark bg-secondary mb-4">
    <a href="" class="navbar-brand">Ronnie Petty</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <router-link to="/" class="nav-item" tag="li" active-class="active" exact><a class="nav-link">Home</a></router-link>
        <router-link to="/user" class="nav-item" tag="li" active-class="active"><a class="nav-link">User</a></router-link>
      </ul>
    </div>
  </nav>
</nav>
</template>

<script>
export default {
}
</script>

<style lang="scss"></style>
